Repository JayFromEsumo/project-wdp-1906-04, pull requests merged in 2019-07, with the labels that each got.

#11 WDP190604-38
  src/partials/50_section-products.html
  src/sass/components/_product-box.scss
Labels: conflicted files

#4 WDP190604-40
  src/partials/70_section-blog-posts.html
  src/sass/components/_post-box.scss
Labels: conflicted files

#14 Wdp190604 49
  src/partials/50_section-products.html
  src/sass/components/_product-box.scss
  src/scripts/app.js
Labels: requested changes

#15 Wdp190604 33
  src/images/ProductsThatFightStatic.jpeg
  src/sass/components/_header.scss
  src/sass/components/_post-box.scss
Labels: conflicted files

#23 Wdp190604 50
  src/partials/50_section-products.html
  src/sass/components/_header.scss
  src/sass/components/_panel-bar.scss
  src/sass/components/_product-box.scss
  src/scripts/app.js
Labels: documentation

#24 Wdp190604 52
  src/images/ProductsThatFightStatic.jpeg
  src/images/ProductsThatFightStatic2.jpeg
  src/images/ProductsThatFightStatic3.jpeg
  src/partials/70_section-blog-posts.html
  src/sass/components/_panel-bar.scss
  src/sass/components/_post-box.scss
  src/scripts/app.js
Labels: documentation

#31 Wdp190604 63
  src/sass/components/_brands.scss
Labels: documentation

#27 Wdp190604 54
  src/partials/20_section-featured.html
  src/sass/components/_section--featured.scss
  src/scripts/app.js
Labels: conflicted files
